# Generated by Django 5.2 on 2025-05-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
