# Generated by Django 5.2 on 2025-05-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_downloadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='download_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='download_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
