# Generated by Django 5.2 on 2025-05-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_downloadhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
