# Generated by Django 5.2 on 2025-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_usersubscription_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
