# Generated by Django 5.2 on 2025-05-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_usersubscription_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='promo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
