# Generated by Django 5.2 on 2025-05-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_usersubscription_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='balance',
            field=models.PositiveIntegerField(default=3500),
        ),
    ]
