# Generated by Django 5.2 on 2025-05-13 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_usersubscription_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('token_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(max_length=100)),
                ('order_description', models.TextField()),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(max_length=10)),
                ('pay_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('invoice_url', models.URLField()),
                ('success_url', models.URLField()),
                ('cancel_url', models.URLField()),
                ('ipn_callback_url', models.URLField(blank=True, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('partially_paid_url', models.URLField(blank=True, null=True)),
                ('payout_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('is_fixed_rate', models.BooleanField(default=False)),
                ('is_fee_paid_by_user', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('collect_user_data', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
