# Generated by Django 5.2 on 2025-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistory',
            name='file',
            field=models.URLField(default=' '),
        ),
    ]
