# Generated by Django 5.2 on 2025-07-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
