# Generated by Django 5.2 on 2025-06-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_response_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='url',
            field=models.CharField(default='ainhub.com', max_length=255),
        ),
    ]
